apiVersion: v2
name: smtp-ext-relay
description: "Simple SMTP server with support for forwarding e-mails using different relays depending on recipient domain"
type: application
version: 0.1.0
appVersion: "main"  # replaced by CI on build stage
