usersSecret:
    kind: SealedSecret # Secret or SealedSecret
    users:
        humhub_1: "bflfmSsYwbpQdmvFcW58dt3dlHY2a4cVjqbjNyS6606QyLL3t3xIC10PFltQYULdbflfmSsYwbpQdmvFcW58dt3dlHY2a4cVjqbjNyS6606QyLL3t3xIC10PFltQYULd"

tlsSecrets:
    create: true
    name: smtp-tls
    kind: Secret  # Secret or SealedSecret
    cert: |
        -----BEGIN PUBLIC KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuRDzqYMehEMD0
        qQWE2wCC3SqLhkb27nacirUfgtS/07LItgVDduL8Elp5xZl41fkWC0m/Fxj88mq8
        cUOlEwQtRD0W2l4QF+f5CjCBVeZwWaaa/0U/kXk726zUErHl6I+WXszR7HT+rhTw
        kzQScAZvH51WCfYgpFeY7noPwxQOH+Eif/hKtjjr5x65hgi3ia+pDWW5rSjGyuVu
        7esK7yUVy4mYX70onCXxW8NgpsqyuAvn3J3xGg3C2+2SwgB9XKUBeHfLRJKVWDYF
        jSbRj6TmA3R9G8WmuyL8a23e3Xe372L8OOacbCkC0z4rNFH250/Ka1cVF61VoPw+
        mhtQJi59AgMBAAECggEAAY2KHWyPWtgTYBrBedWZw5DE+ElSCJFHbU2vH4DC9JKm
        XTOCCH/etfBT7hHctD7z4UZoedNy3Y4rdVJtD+ODfgPFp5Z6kBombwmwNPbW/tlN
        qsPrkg1xzx6+A4XHIA1aejSODrDUuhBDD4HATQnChOr7M/ESyGeugCZf4BQU8atD
        ShMCm9T9BYZhOM3Nj57hTZ0DmvdTQB7ENzqJgnNc4kcvXHwVrqVu/onnx0CkpSEQ
        bf0yFQnRYirAV+6o+yGnoVkCUWNc43DxyAkoGWFc+OR+fhypUJS20QcABCOA+lD7
        lJ9MJlv71wD3CfVi5t9M8LqPAGWRC/XuBUDuShDr4QKBgQDaqQpE4ioBGC3obM93
        HEETovIxaQ+/IR2h2WL47dupnTAJha01Q/xBjeyrlS8JoYKT9jI2O+4a9xK6k1bK
        +8MVuTvtvP/uyCyzKZT28aKeR2pL5to8H5+MSxeCxbjNwrhnXv1QnwTiYuqzvaqc
        ztKVIGiD8sBfGVplfaot6CFdOwKBgQDMBnqpZTet9U0Mk0cQ+4dT6soDOkoHstHw
        THIS/uKtmeRs7h5LFFrKGWVPZZWbd+ljUWQ8pW9FNq+M/9sHIcJuZ4SThoSEw5lw
        5TO+ix7YCqr2WUHJ3CLd0di4oF4JmS1iXNkOP/mZervPSIeTumc45djcW/R7J67t
        B4is+CVHpwKBgQCio1z6A2bOzZdH67ccly1oV6jhS43k0dLikXjmQrVCIaKbUoyU
        s+6rK88/iIUmGrWvLE4IvObLs76AfBrwe/aM7+w9VnjeuJFW6bTdQLl+FQxhTGJC
        mhroFOp14G8mzJCwgpzUHJNbd8uuyYJfhA5p0WMr0aF4mrj8CE5OOvymBQKBgQC1
        9Z1WEGiNI/YYng1Gjx2NcRvDryuxHAFyb6tZV6swqsx3fhLUYQ3rqqSZH/9Czbn/
        kupz0BOhxfjhJprgDHLMZlRuAg2UHqJtdm0kpgzXHwSEeuxarJMIBAxl9NiJdOxu
        CmKm+9WO1VBEuOn5jchbjVpQhU5Qu/6ddRenNBSDhwKBgD7Zir/5Wi3jVmRpgZTO
        dFoHWvWx+jH8VUzIYHpK4vkDDQ0pqGAEDMWcsGMP+V4hPrf5ePvVn3tzuh5ZMvDI
        aciQlTpZSc0oucgNiTAtZtiQcALOBJmbJr6qEHMRons/JWr3gD35wvjwpNIzMNrd
        xCjiveLdlpj9WDiDbHNFihj8
        -----END PUBLIC KEY-----
    key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuRDzqYMehEMD0
        qQWE2wCC3SqLhkb27nacirUfgtS/07LItgVDduL8Elp5xZl41fkWC0m/Fxj88mq8
        cUOlEwQtRD0W2l4QF+f5CjCBVeZwWaaa/0U/kXk726zUErHl6I+WXszR7HT+rhTw
        kzQScAZvH51WCfYgpFeY7noPwxQOH+Eif/hKtjjr5x65hgi3ia+pDWW5rSjGyuVu
        7esK7yUVy4mYX70onCXxW8NgpsqyuAvn3J3xGg3C2+2SwgB9XKUBeHfLRJKVWDYF
        jSbRj6TmA3R9G8WmuyL8a23e3Xe372L8OOacbCkC0z4rNFH250/Ka1cVF61VoPw+
        mhtQJi59AgMBAAECggEAAY2KHWyPWtgTYBrBedWZw5DE+ElSCJFHbU2vH4DC9JKm
        XTOCCH/etfBT7hHctD7z4UZoedNy3Y4rdVJtD+ODfgPFp5Z6kBombwmwNPbW/tlN
        qsPrkg1xzx6+A4XHIA1aejSODrDUuhBDD4HATQnChOr7M/ESyGeugCZf4BQU8atD
        ShMCm9T9BYZhOM3Nj57hTZ0DmvdTQB7ENzqJgnNc4kcvXHwVrqVu/onnx0CkpSEQ
        bf0yFQnRYirAV+6o+yGnoVkCUWNc43DxyAkoGWFc+OR+fhypUJS20QcABCOA+lD7
        lJ9MJlv71wD3CfVi5t9M8LqPAGWRC/XuBUDuShDr4QKBgQDaqQpE4ioBGC3obM93
        HEETovIxaQ+/IR2h2WL47dupnTAJha01Q/xBjeyrlS8JoYKT9jI2O+4a9xK6k1bK
        +8MVuTvtvP/uyCyzKZT28aKeR2pL5to8H5+MSxeCxbjNwrhnXv1QnwTiYuqzvaqc
        ztKVIGiD8sBfGVplfaot6CFdOwKBgQDMBnqpZTet9U0Mk0cQ+4dT6soDOkoHstHw
        THIS/uKtmeRs7h5LFFrKGWVPZZWbd+ljUWQ8pW9FNq+M/9sHIcJuZ4SThoSEw5lw
        5TO+ix7YCqr2WUHJ3CLd0di4oF4JmS1iXNkOP/mZervPSIeTumc45djcW/R7J67t
        B4is+CVHpwKBgQCio1z6A2bOzZdH67ccly1oV6jhS43k0dLikXjmQrVCIaKbUoyU
        s+6rK88/iIUmGrWvLE4IvObLs76AfBrwe/aM7+w9VnjeuJFW6bTdQLl+FQxhTGJC
        mhroFOp14G8mzJCwgpzUHJNbd8uuyYJfhA5p0WMr0aF4mrj8CE5OOvymBQKBgQC1
        9Z1WEGiNI/YYng1Gjx2NcRvDryuxHAFyb6tZV6swqsx3fhLUYQ3rqqSZH/9Czbn/
        kupz0BOhxfjhJprgDHLMZlRuAg2UHqJtdm0kpgzXHwSEeuxarJMIBAxl9NiJdOxu
        CmKm+9WO1VBEuOn5jchbjVpQhU5Qu/6ddRenNBSDhwKBgD7Zir/5Wi3jVmRpgZTO
        dFoHWvWx+jH8VUzIYHpK4vkDDQ0pqGAEDMWcsGMP+V4hPrf5ePvVn3tzuh5ZMvDI
        aciQlTpZSc0oucgNiTAtZtiQcALOBJmbJr6qEHMRons/JWr3gD35wvjwpNIzMNrd
        xCjiveLdlpj9WDiDbHNFihj8
        -----END PRIVATE KEY-----
    ca: |
        -----BEGIN PUBLIC KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuRDzqYMehEMD0
        qQWE2wCC3SqLhkb27nacirUfgtS/07LItgVDduL8Elp5xZl41fkWC0m/Fxj88mq8
        cUOlEwQtRD0W2l4QF+f5CjCBVeZwWaaa/0U/kXk726zUErHl6I+WXszR7HT+rhTw
        kzQScAZvH51WCfYgpFeY7noPwxQOH+Eif/hKtjjr5x65hgi3ia+pDWW5rSjGyuVu
        7esK7yUVy4mYX70onCXxW8NgpsqyuAvn3J3xGg3C2+2SwgB9XKUBeHfLRJKVWDYF
        jSbRj6TmA3R9G8WmuyL8a23e3Xe372L8OOacbCkC0z4rNFH250/Ka1cVF61VoPw+
        mhtQJi59AgMBAAECggEAAY2KHWyPWtgTYBrBedWZw5DE+ElSCJFHbU2vH4DC9JKm
        XTOCCH/etfBT7hHctD7z4UZoedNy3Y4rdVJtD+ODfgPFp5Z6kBombwmwNPbW/tlN
        qsPrkg1xzx6+A4XHIA1aejSODrDUuhBDD4HATQnChOr7M/ESyGeugCZf4BQU8atD
        ShMCm9T9BYZhOM3Nj57hTZ0DmvdTQB7ENzqJgnNc4kcvXHwVrqVu/onnx0CkpSEQ
        bf0yFQnRYirAV+6o+yGnoVkCUWNc43DxyAkoGWFc+OR+fhypUJS20QcABCOA+lD7
        lJ9MJlv71wD3CfVi5t9M8LqPAGWRC/XuBUDuShDr4QKBgQDaqQpE4ioBGC3obM93
        HEETovIxaQ+/IR2h2WL47dupnTAJha01Q/xBjeyrlS8JoYKT9jI2O+4a9xK6k1bK
        +8MVuTvtvP/uyCyzKZT28aKeR2pL5to8H5+MSxeCxbjNwrhnXv1QnwTiYuqzvaqc
        ztKVIGiD8sBfGVplfaot6CFdOwKBgQDMBnqpZTet9U0Mk0cQ+4dT6soDOkoHstHw
        THIS/uKtmeRs7h5LFFrKGWVPZZWbd+ljUWQ8pW9FNq+M/9sHIcJuZ4SThoSEw5lw
        5TO+ix7YCqr2WUHJ3CLd0di4oF4JmS1iXNkOP/mZervPSIeTumc45djcW/R7J67t
        B4is+CVHpwKBgQCio1z6A2bOzZdH67ccly1oV6jhS43k0dLikXjmQrVCIaKbUoyU
        s+6rK88/iIUmGrWvLE4IvObLs76AfBrwe/aM7+w9VnjeuJFW6bTdQLl+FQxhTGJC
        mhroFOp14G8mzJCwgpzUHJNbd8uuyYJfhA5p0WMr0aF4mrj8CE5OOvymBQKBgQC1
        9Z1WEGiNI/YYng1Gjx2NcRvDryuxHAFyb6tZV6swqsx3fhLUYQ3rqqSZH/9Czbn/
        kupz0BOhxfjhJprgDHLMZlRuAg2UHqJtdm0kpgzXHwSEeuxarJMIBAxl9NiJdOxu
        CmKm+9WO1VBEuOn5jchbjVpQhU5Qu/6ddRenNBSDhwKBgD7Zir/5Wi3jVmRpgZTO
        dFoHWvWx+jH8VUzIYHpK4vkDDQ0pqGAEDMWcsGMP+V4hPrf5ePvVn3tzuh5ZMvDI
        aciQlTpZSc0oucgNiTAtZtiQcALOBJmbJr6qEHMRons/JWr3gD35wvjwpNIzMNrd
        xCjiveLdlpj9WDiDbHNFihj8
        -----END PUBLIC KEY-----
