# todo: TLS secrets
{{- if .Values.tlsSecrets.create }}

{{- if eq .Values.tlsSecrets.kind "SealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ .Values.tlsSecrets.name }}
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
spec:
    encryptedData:
        cert: {{ .Values.tlsSecrets.cert }}
        key: {{ .Values.tlsSecrets.key }}
        ca: {{ .Values.tlsSecrets.ca }}

{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.tlsSecrets.name }}
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
data:
    cert: {{ .Values.tlsSecrets.cert | b64enc }}
    key: {{ .Values.tlsSecrets.key | b64enc }}
    ca: {{ .Values.tlsSecrets.ca | b64enc }}

{{- end }}
{[- end ]}
