{{- if .Values.tlsSecrets.create }}
{{- if eq .Values.tlsSecrets.kind "SealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ .Values.tlsSecrets.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
spec:
    encryptedData:
        cert: {{ .Values.tlsSecrets.cert }}
        key: {{ .Values.tlsSecrets.key }}
        ca: {{ .Values.tlsSecrets.ca }}

{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.tlsSecrets.name }}
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
data:
    tls.crt: {{ .Values.tlsSecrets.cert | b64enc }}
    tls.key: {{ .Values.tlsSecrets.key | b64enc }}
    ca.crt: {{ .Values.tlsSecrets.ca | b64enc }}

{{- end }}
{{- end }}
