{{- if eq .Values.usersSecret.kind "SealedSecret" }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: {{ include "smtp-ext-relay.fullname" . }}-users-secret
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
spec:
    encryptedData:
        {{- range $key, $value := .Values.usersSecret.users }}
        {{ $key }}: "{{ $value }}"
        {{- end }}

{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "smtp-ext-relay.fullname" . }}-users-secret
    labels:
        {{- include "smtp-ext-relay.labels" . | nindent 8 }}
data:
    {{- range $key, $value := .Values.usersSecret.users }}
    {{ $key }}: "{{ $value | b64enc }}"
    {{- end }}

{{- end }}
