name: Test and release
on:
    push:
    workflow_dispatch:
        inputs: {}

jobs:
    container-image:
        uses: riotkit-org/.github/.github/workflows/release.container.yaml@release-1
        if: |
            always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        with:
            osVariant: ubuntu-22.04
            intermediateArtifactsPath: ""
            dockerImage: "ghcr.io/riotkit-org/smtpd"

    helm:
        uses: riotkit-org/.github/.github/workflows/release.helm.yaml@release-1
        needs: ["container-image"]
        if: |
            always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
        with:
            chartPath: helm/smtp-ext-relay
            chartName: smtpd
            enableHelmDocs: true
